server:
  port: 8081


app-username: test

###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

    ###因为该应用为注册中心，不会注册自己
    register-with-eureka: true
    ###是否需要从eureka上获取注册信息
    fetch-registry: true
  instance:
    appname: fegin-flight-service
    virtual-host-name: fegin-flight-service
    secure-virtual-host-name: fegin-flight-service
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.haina.flight.price.model
  mapperLocations: classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flight?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
